### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by CalvinScott**
Readme is out of date

### CODE REVIEW

**Comment by CalvinScott** [comment]
@switters @slajax Please review whenever you're bored enough

**Comment by switters** [comment]
@CalvinScott if you could figure out how to update the demo, that would be grreatt.. ** sips coffee ** :coffee:

**Comment by CalvinScott** [comment]
@switters I'll take a shot at those TPS reports tomorrow, Lumbergh

**Comment by slajax** [comment]
@switters can we future proof this a bit for the changes coming in new new authd? ie: options.vendor etc?

**Comment by slajax** [comment]
@CalvinScott Can you speak to @switters about the new stuff that is going in and make sure the Readme accounts for it? Otherwise it'll just be out of date as soon as they land the next PR.

**Comment by CalvinScott** [comment]
@slajax Sure thing

**Comment by switters** [comment]
@CalvinScott @slajax - This will be the case. The 'Retsly Secure Sign On' flow we're working on atm will substantially change retsly-js-auth. Perhaps it's best to put a pin in this until those changes land.

**Comment by slajax** [comment]
Ok, lets just land these since they are trivial but make sure that it's all updated when those new changes land. @CalvinScott take it down :+1:

**Pull request merged**
