### PR TITLE
Scopes Integration

### PR DESCRIPTION
**Pull request by switters**
Add scopes param to the request string. Relates to retsly issue #991 - Scopes exploration.

### CODE REVIEW

**Comment by switters** [comment]
@slajax - This also pertains to retsly/retsly #991.

**Comment by CMClay** [comment]
:+1:

**Comment by CMClay** [comment]
@switters I'll merge this into #22 and tag the release.

**Comment by switters** [comment]
@Jkhwan - review?

**Comment by Jkhwan** [comment]
:+1:

**Pull request merged**
