### PR TITLE
response_type should be variable

### PR DESCRIPTION
**Pull request by Jkhwan**
response_type should be either =token or =code. Currently, only code is supported. This is due to server-side issues. Ref: Retsly/retsly#1300.

- [x] OAuth implementation on server-side should allow for a 'token' response type.
- [x] Change js-auth code to request `response_type=token`.

### CODE REVIEW

**Comment by Jkhwan** [comment]
@slajax @CMClay  review please

**Comment by CMClay** [comment]
:+1:

**Comment by Jkhwan** [comment]
@switters quick review please

**Comment by switters** [comment]
:+1: sweet!

**Pull request merged**
