### PR TITLE
Increase width, height

### PR DESCRIPTION
**Pull request by switters**
- [x] Increase size of dialogue window to width=650, height=500

### CODE REVIEW

**Comment by switters** [comment]
@kregensberg - review?

**Comment by kregensberg** [comment]
Width should be 650 - sorry, did i write 651?

**Comment by Jkhwan** [comment]
@kregensberg if i remember correctly, you are fixing the css such that it all fits in the popup so we can close this issue right?

**Comment by kregensberg** [comment]
Yup!

**Pull request closed without merging**
